name: Publish

on:
  release:
    types: [published]

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:

  publish_macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Publish test-that-macro to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p test-that-macro

  publish:
    needs: publish_macro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Publish test-that to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p test-that
